
version: '3.1'
services :
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pets
      POSTGRES_PASSWORD: p3tsp4c3
      POSTGRES_DB: pets01
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080